language: python
python:
  - "2.7"
before_script:
  - "mysql -e 'create database funicular_test;'"
before_install:
  - "pip install -r requirements.txt"
  - "pip install MySQL-Python"
install:
  - "pip install coveralls"
script:
  - coverage run -m unittest discover tests
after_success:
  - coveralls
branches:
  only:
  - develop
services:
  - mysql